### ISSUE TITLE
پیشنهاد انتشار

### ISSUE THREAD

**Issue by omidgolparvar** [Rminsh/JalaliCalendar#1]
<div dir="rtl">
سلام. خسته نباشی.

بنظرم برنامه جالب و مفیدی شده.😊 
قصد نداری روی مثلا تست‌فلایت منتشر کنی؟

</div>

**Comment by Rminsh** [comment]
سلام امیدجان
ممنونم
قربانت ، چرا اتفاقا به یکی از دوستانم سپردم منتشرش کنه به خاطر مشغله کاری طول کشیده 😅
خیلی دوست دارم که به عنوان یه اپ مینیمال به جای خوبی برسه 😁

**Comment by omidgolparvar** [comment]
<div dir="rtl">
خیلی هم عالی. 

فقط یه مورد. اونم این که آیا آغوش‌ات برای همکاری بازه؟! 😅😁
توی ذهنم بود که اگه ویژگی خوبی به ذهنم رسید، بهش اضافه کنم. مثلا مبدل تاریخ.

</div>

**Comment by Rminsh** [comment]
آره حتما 👌😍
ممنونم ازت
